Description of nt_demean
Home > NoiseTools > nt_demean.m
nt_demean
PURPOSE
[y,mn]=nt_demean(x,w) - remove weighted mean over cols
SYNOPSIS
function [x,mn]=nt_demean(x,w)
DESCRIPTION
[y,mn]=nt_demean(x,w) - remove weighted mean over cols
  w is optional
  if w is a vector with fewer samples than size(x,1), it is interpreted as
  a vector of indices to be set to 1, the others being set to 0.
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_fold y=fold(x,epochsize) - fold 2D to 3D
nt_greetings nt_greetings - display message the first time the toolbox is used
nt_unfold y=nt_fold(x) - unfold 3D to 2D
nt_vecadd y=nt_vecadd(x,v) - add vector to all rows or columns of matrix
nt_vecmult y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
This function is called by:
nt_demean2 y=nt_demean2(x,w) - remove mean of each row and page
nt_destep [y,stepList]=nt_destep(x,thresh,guard,depth,minstep) - remove step glitch from MEG data
nt_detrend [y,w,r]=nt_detrend(x,order,w,basis,thresh,niter) - robustly remove trend
nt_dprime [d,err_rate,perm,area_roc,roc]=nt_dprime(x,y,jd_flag) - calculate d' (discriminability) of two distributions
nt_idx_disp nt_idx_disp(name,field,explainflag) - display contents of index file
nt_inpaint function y=nt_inpaint(x,w) - weighted interpolation based on correlation structure
nt_iplot [hh,ii]=nt_iplot(fname) - plot data file based on index
nt_outliers [w,y]=nt_outliers(x,w,thresh,niter) - detect outliers based on weighted correlation structure
nt_regw [b,z]=nt_regw(y,x,w) - weighted regression
nt_sgram [s,f,t]=nt_sgram(x,window,noverlap,nfft,sr,flags) - spectrogram
nt_sns y=nt_sns(x,nneigbors,skip,w) - sensor noise suppression
nt_split [idx,score_vector,score]=nt_split(x,depth,thresh,guard,minstep) - split time series into intervals
nt_split_jd [idx,score_vector,todss]=nt_split_dss(x,thresh,depth) - segmentation based on joint diagonalization
nt_star [y,w,ww]=nt_star(x,thresh,closest,depth) - sensor noise suppression
nt_star2 [y,w,ww]=nt_star2(x,thresh,closest,w) - sensor noise suppression
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsregress [z,idx]=nt_tsregress(x,y,shifts,xw,yw,keep,threshold) - time-shift regression
SOURCE CODE
function [x,mn]=nt_demean(x,w)
%[y,mn]=nt_demean(x,w) - remove weighted mean over cols
%
%  w is optional
%
%  if w is a vector with fewer samples than size(x,1), it is interpreted as
%  a vector of indices to be set to 1, the others being set to 0.
%
% NoiseTools
if nargin<2; w=[]; end
if nargin<1; error('!');end
nt_greetings;
if iscell(x);
    cellFlag=1;
    x=nt_cell_to_3D(x);
    w=nt_cell_to_3D(x);
else
    cellFlag=0;
end
if ~isempty(w) && numel(w)<size(x,1)
    w=w(:);
    % interpret w as array of indices to set to 1
    if min(w)<1 || max(w)>size(x,1);
        error('w interpreted as indices but values are out of range');
    end
    ww=zeros(size(x,1),1);
    ww(w)=1;
    w=ww;
end
if size(w,3)~=size(x,3);
    if size(w,3)==1 && size(x,3)~=1;
        w=repmat(w,[1,1,size(x,3)]);
    else
        error('W should have same npages as X, or else 1');
    end
end
[m,n,o]=size(x);
x=nt_unfold(x);
if isempty(w);
    mn=mean(double(x),1);
    x=nt_vecadd(x,-mn);
else
    w=nt_unfold(w);
    if size(w,1)~=size(x,1)
        error('X and W should have same nrows');
    end
    if size(w,2)==1;
        mn=sum(nt_vecmult(double(x),w),1) ./ (sum(w,1)+eps);
    elseif size(w,2)==n;
        mn=sum(x.*w) ./ (sum(w,1)+eps);
    else
        error('W should have same ncols as X, or else 1');
    end
    %y=bsxfun(@minus,x,mn);
    x=nt_vecadd(x,-mn);
end
x=nt_fold(x,m);
if cellFlag
    x=nt_3D_to_cell(x);
end