Description of nt_detrend_robust_old
Home > NoiseTools > nt_detrend_robust_old.m
nt_detrend_robust_old
PURPOSE
[y,w]=nt_detrend_robust(x,order,w,basis,thresh,percentage) - remove polynomial or sinusoidal trend
SYNOPSIS
function [x,w]=ntdetrend_robust(x,order,w,basis,thresh,niter)
DESCRIPTION
[y,w]=nt_detrend_robust(x,order,w,basis,thresh,percentage) - remove polynomial or sinusoidal trend
  y: detrended data
  x: raw data
  order: order of polynomial
  w: weight
  basis: 'polynomials' [default] or 'sinusoids'
  thresh: threshold for outliers [default: 2 sd]
  niter: number of iterations [default: 2]
CROSS-REFERENCE INFORMATION
This function calls:
nt_demean [y,mn]=nt_demean(x,w) - remove weighted mean over cols
nt_detrend_robust [y,w]=nt_detrend_robust(x,order,w,basis,thresh,niter) - remove polynomial or sinusoidal trend
nt_normcol [y,norm]=nt_normcol(x,w) - normalize each column so its weighted msq is 1
This function is called by:
SOURCE CODE
function [x,w]=ntdetrend_robust(x,order,w,basis,thresh,niter)
%[y,w]=nt_detrend_robust(x,order,w,basis,thresh,percentage) - remove polynomial or sinusoidal trend
%
%  y: detrended data
%
%  x: raw data
%  order: order of polynomial
%  w: weight
%  basis: 'polynomials' [default] or 'sinusoids'
%  thresh: threshold for outliers [default: 2 sd]
%  niter: number of iterations [default: 2]
%% arguments
if nargin<2; error('!'); end
if nargin<3; w=[]; end
if nargin<4||isempty(basis); basis='polynomials'; end
if nargin<5||isempty(thresh); thresh=1.5; end
if nargin<6||isempty(niter); niter=4; end
dims=size(x);
x=x(:,:); % concatenates dims >= 2
%% regressors
switch basis
    case 'polynomials'
        r=zeros(size(x,1),numel(order));
        lin=linspace(-1,1,size(x,1));
        for k=1:order
            r(:,k)=lin.^k;
        end
    case 'sinusoids'
        r=zeros(size(x,1),numel(order)*2);
        lin=linspace(-1,1,size(x,1));
        for k=1:order
            r(:,2*k-1)=sin(2*pi*k*lin/2);
            r(:,2*k)=cos(2*pi*k*lin/2);
        end
    otherwise
        error('!');
end
r=nt_demean(r);
r=nt_normcol(r);
%% give weights same geometry as data
if size(w)==size(x)
    ; % OK
elseif isempty(w)
    w=ones(size(x));
else
    w=repmat(w,1,size(x,2)); % to each channel its own weight
end
figure(1); clf;
figure(2); clf;
%% remove trends
for iChan=1:size(x,2) % detrend each channel individually
    xx=x(:,iChan);
    ww=w(:,iChan);
    for iIter=1:niter
        www=ww;
        for iRegressor = 1:size(r,2) % remove regressors one by one
            % weight data, remove mean
            xxx=xx.*www;
            avg=sum(xxx)/sum(www);
            xxx=xxx-avg;
            xxx=xxx.*www;
            % weight basis, remove mean, PCA, normalize
            rr=r(:,iRegressor);
            rr=nt_demean(rr,www);
            rr=nt_normcol(rr,www);
            a=xxx' * rr / sum(www); % cross product with basis
            y=rr*a'; % project
            y=y+avg; % restore mean
            d=xx-y;
            xx=d;
            www=min(www,(abs(d)<=thresh*std(d)));
            figure(1)
            subplot 311; plot([xx,y]);
            subplot 312; plot(d); hold on
            subplot 313; plot(www); ylim([-0.1 1.1]); pause
            disp(mean(d.^2.*www))
        end
        ww=min(ww,www);
        xx=xx-y;
        %figure(2); plot([xx]); hold on
    end
    x(:,iChan)=xx;
    w(:,iChan)=ww;
end
x=reshape (x,dims);
%% test code
if 0
    x=(1:100)';
    nt_detrend_robust(x,2,[],[],[],[],[]);
end