Description of nt_find_outliers
Home > NoiseTools > nt_find_outliers.m
nt_find_outliers
PURPOSE
w=nt_find_outliers(x,toobig1,toobig2) - find outliers (glitches, etc.).
SYNOPSIS
function w=nt_find_outliers(x,toobig1,toobig2);
DESCRIPTION
w=nt_find_outliers(x,toobig1,toobig2) - find outliers (glitches, etc.).
  w: mask matrix (0: bad, 1: good)
  x: data
  toobig1: absolute threshold for glitches
  toobig2: relative threshold for outliers
 Outliers are found independently for each channel.
 Data can be 2D or 3D.  If 3D, data are folded and variance stats are
 calculated over folded (concatenated) columns.  W is same size as X.
 TOOBIG1 is an absolute threshold that applies to absolute value.  TOOBIG2
 is a threshold that applies to absolute value relative to mean absolute value.
 For any value above threshold the mask is set to zero, else one.
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_demean [y,mn]=nt_demean(x,w) - remove weighted mean over cols
nt_fold y=fold(x,epochsize) - fold 2D to 3D
nt_unfold y=nt_fold(x) - unfold 3D to 2D
nt_wmean y=nt_wmean(x,w,dim) - weighted average
This function is called by:
SOURCE CODE
function w=nt_find_outliers(x,toobig1,toobig2);
%w=nt_find_outliers(x,toobig1,toobig2) - find outliers (glitches, etc.).
%
%  w: mask matrix (0: bad, 1: good)
%
%  x: data
%  toobig1: absolute threshold for glitches
%  toobig2: relative threshold for outliers
%
% Outliers are found independently for each channel.
%
% Data can be 2D or 3D.  If 3D, data are folded and variance stats are
% calculated over folded (concatenated) columns.  W is same size as X.
%
% TOOBIG1 is an absolute threshold that applies to absolute value.  TOOBIG2
% is a threshold that applies to absolute value relative to mean absolute value.
% For any value above threshold the mask is set to zero, else one.
%
% NoiseTools
if nargin<2; error('!'); return; end
if nargin<3; toobig2=[]; end
[m,n,o]=size(x);
x=nt_unfold(x);
% remove mean
x=nt_demean(x);
% apply absolute threshold:
w=ones(size(x));
if ~ isempty(toobig1);
    w(find(abs(x)>toobig1))=0;
    x=nt_demean(x,w);
    w(find(abs(x)>toobig1))=0;
    x=nt_demean(x,w);
    w(find(abs(x)>toobig1))=0;
    x=nt_demean(x,w);
else
    w=ones(size(x));
end
% apply relative threshold
if ~isempty(toobig2);
    X=nt_wmean(x.^2,w);
    X=repmat(X,size(x,1),1);
    idx=find(x.^2>(X*toobig2));
    w(idx)=0;
end
w=nt_fold(w,m);