Description of nt_greetings
Home > NoiseTools > nt_greetings.m
nt_greetings
PURPOSE
nt_greetings - display message the first time the toolbox is used
SYNOPSIS
function nt_greetings(reset)
DESCRIPTION
nt_greetings - display message the first time the toolbox is used
CROSS-REFERENCE INFORMATION
This function calls:
nt_version
This function is called by:
nt_bsplot nt_bsplot(x,sds,style,abscissa,zeroflag,rmsflag) - plot average with bootstrap standard deviation
nt_cca [A,B,R]=nt_cca(x,y,shifts,C,m,thresh) - canonical correlation
nt_deboing y=nt_deboing(x,events) - fit, remove ringing associated with events
nt_demean [y,mn]=nt_demean(x,w) - remove weighted mean over cols
nt_destep [y,stepList]=nt_destep(x,thresh,guard,depth,minstep) - remove step glitch from MEG data
nt_detrend [y,w,r]=nt_detrend(x,order,w,basis,thresh,niter) - robustly remove trend
nt_dss0 [todss,pwr1,pwr2]=nt_dss0(c0,c1,keep1,keep2) - dss from covariance
nt_dss_repeat_cluster y=nt_dss_repeat_cluster(x,nkeep,cluster_size) - dss within clusters
nt_fold y=fold(x,epochsize) - fold 2D to 3D
nt_idx_disp nt_idx_disp(name,field,explainflag) - display contents of index file
nt_index [status,p]=nt_index(name,p,forceUpdate) - index data files & directories
nt_inpaint function y=nt_inpaint(x,w) - weighted interpolation based on correlation structure
nt_interpolate_bad_channels y=interpolate_bad_channels(x,iBad,coordinates,n) - interpolate bad channels from good
nt_iplot [hh,ii]=nt_iplot(fname) - plot data file based on index
nt_morton [iMorton,toMorton]=nt_morton(nrows,ncols) - indices for Morton scan of image
nt_multismooth z=nt_multismooth(x,smooth,alignment) - apply multiple smoothing kernels
nt_narrowband_scan A=nt_narrowband_scan(x,freqs,sr,Q,plotflag) - scan for narrowband components using DSS
nt_outliers [w,y]=nt_outliers(x,w,thresh,niter) - detect outliers based on weighted correlation structure
nt_pca [z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
nt_proximity [closest,d]=nt_proximity(coordinates,N) - distance to neighboring channels
nt_sgram [s,f,t]=nt_sgram(x,window,noverlap,nfft,sr,flags) - spectrogram
nt_smooth y=nt_smooth(x,T,nIterations,nodelayflag) - smooth by convolution with square window
nt_sns y=nt_sns(x,nneigbors,skip,w) - sensor noise suppression
nt_sns_cluster y=nt_sns_cluster(x,nneigbors,cluster_size) - sensor noise suppression within clusters
nt_star [y,w,ww]=nt_star(x,thresh,closest,depth) - sensor noise suppression
nt_star2 [y,w,ww]=nt_star2(x,thresh,closest,w) - sensor noise suppression
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_unfold y=nt_fold(x) - unfold 3D to 2D
SOURCE CODE
function nt_greetings(reset)
%nt_greetings - display message the first time the toolbox is used
persistent nt_greeted
if nargin>0; nt_greeted=reset; return; end
if isempty(nt_greeted)
    display(' ')
    display(['NoiseTools, version ',nt_version]);
    display('http://audition.ens.fr/adc/NoiseTools');
    display('Please cite relevant methods papers.');
    display(' ');
    nt_greeted=1;
end