Description of nt_narrowband_scan
Home > NoiseTools > nt_narrowband_scan.m
nt_narrowband_scan
PURPOSE
A=nt_narrowband_scan(x,freqs,sr,Q,plotflag) - scan for narrowband components using DSS
SYNOPSIS
function A=nt_narrowband_scan(x,freqs,sr,Q,plotflag,yulewalk_order)
DESCRIPTION
A=nt_narrowband_scan(x,freqs,sr,Q,plotflag) - scan for narrowband components using DSS
  A: cell array of DSS matrices
  x: data (time*channels or time*channels*trials)
  freqs: Hz, array of bias frequencies
  sr: Hz, sampling rate
  Q: quality factors of scanning filter (default: [8 4])
  plotflag: if true plot (default: 1)
  yulewalk_order: if present apply inverse filtering with this order
 If no output arguments, plots spectra of first DSS components for each
 bias
CROSS-REFERENCE INFORMATION
This function calls:
nt_bias_filter [c0,c1]=nt_bias_filter(x,B,A) - covariance with and w/o filter bias
nt_dss0 [todss,pwr1,pwr2]=nt_dss0(c0,c1,keep1,keep2) - dss from covariance
nt_filter_peak [B,A] = nt_filter_peak(Wo,Q) - second order resonator filter
nt_greetings nt_greetings - display message the first time the toolbox is used
nt_mmat y=nt_mmat(x,m) - matrix multiplication (with convolution)
nt_normcol [y,norm]=nt_normcol(x,w) - normalize each column so its weighted msq is 1
nt_spect_plot2 nt_spect_plot2 - plot power spectrum
This function is called by:
SOURCE CODE
function A=nt_narrowband_scan(x,freqs,sr,Q,plotflag,yulewalk_order)
%A=nt_narrowband_scan(x,freqs,sr,Q,plotflag) - scan for narrowband components using DSS
%
%  A: cell array of DSS matrices
%
%  x: data (time*channels or time*channels*trials)
%  freqs: Hz, array of bias frequencies
%  sr: Hz, sampling rate
%  Q: quality factors of scanning filter (default: [8 4])
%  plotflag: if true plot (default: 1)
%  yulewalk_order: if present apply inverse filtering with this order
%
% If no output arguments, plots spectra of first DSS components for each
% bias
%
nt_greetings;
if nargin<6; yulewalk_order=[]; end
if nargin<5; plotflag=[]; end
if nargin<4||isempty(Q); Q=[8 4]; end
if nargin<3; error('!'); end
freqs=freqs(:);
current_figure=get(0,'CurrentFigure');
A={};
for iFreqs=1:numel(freqs)
    freq=freqs(iFreqs);
    [b,a]=nt_filter_peak(freq/(sr/2),Q(1));
    [c0,c1]=nt_bias_filter(x,b,a);
    if numel(Q)==2
        [b,a]=nt_filter_peak(freq/(sr/2),Q(2));
        [~,c0]=nt_bias_filter(x,b,a);
    end
    [todss,pwr0,pwr1]=nt_dss0(c0,c1);
    if 1; figure(100); clf; plot(pwr1./pwr0,'.-'); title([num2str(freq), 'Hz bias']); ylabel('score');  drawnow;end
    A{iFreqs}=todss;
end
if ~nargout || ~isempty(plotflag)
    if isempty(current_figure);
        figure;
    else
        figure(current_figure);
    end
    AA=zeros(size(x,2),numel(freqs));
    for iFreqs=1:numel(freqs)
        AA(:,iFreqs)=A{iFreqs}(:,1);
    end
    x=nt_mmat(x,AA);
    nfft=2.^nextpow2(size(x,1)+1)/2;
    MAX_NFFT=1024;
    nfft=min(nfft,MAX_NFFT);
    nt_spect_plot2(nt_normcol(x),nfft,[],[],sr);
    K=round(numel(freqs)/6);
    set(gca,'ytick',1:K:numel(freqs), 'yticklabel',num2str(freqs(1:K:end), '%.3g')); ylabel('Hz');
    set(gca,'xgrid','on','xminortick','on');
    drawnow;
end
if ~nargout;     clear A; end