Description of nt_pca0
Home > NoiseTools > nt_pca0.m
nt_pca0
PURPOSE
[topcs,pwr,y]=nt_pca0(x,shifts,nkeep,threshold,w) - time-shift pca
SYNOPSIS
function [topcs,pwr,y]=nt_pca0(x,shifts,nkeep,threshold,w)
DESCRIPTION
[topcs,pwr,y]=nt_pca0(x,shifts,nkeep,threshold,w) - time-shift pca
  topcs: matrix to convert data to PCs
  pwr: power per PC
  y: PCs
  x: data matrix
  shifts: array of shifts to apply
  nkeep: number of PCs to keep
  w: weight (see nt_cov)
  threshold: remove components with normalized eigenvalues smaller than threshold (default: 0)
 mean is NOT removed prior to processing
CROSS-REFERENCE INFORMATION
This function calls:
nt_cov [c,tw]=nt_cov(x,shifts,w) - time shift covariance
nt_mmat y=nt_mmat(x,m) - matrix multiplication (with convolution)
nt_pca0 [topcs,pwr,y]=nt_pca0(x,shifts,nkeep,threshold,w) - time-shift pca
nt_pcarot [topcs,eigenvalues]=pcarot(cov,nkeep,threshold,N) - PCA matrix from covariance
This function is called by:
nt_pca0 [topcs,pwr,y]=nt_pca0(x,shifts,nkeep,threshold,w) - time-shift pca
nt_pca_kmeans [topcs,pwr]=nt_pca_kmeans(x,nkeep) - PCA preceded by kmeans for speed
nt_qca0 [tosquares,quads,D]=nt_qca0(x,npcs,nsmooth,nquads) - maximize induced power using quadratic component analysis
nt_qca02 [tosquare,quad,tosquare2,quad2,D]=nt_qca02(x,npcs,nsmooth) - maximize induced power using quadratic component analysis
nt_qpca0 [tosquares,quads,D]=nt_qpca0(x,npcs,nsmooth,nquads) - quadratic PCA
nt_split_jd [idx,score_vector,todss]=nt_split_dss(x,thresh,depth) - segmentation based on joint diagonalization
SOURCE CODE
function [topcs,pwr,y]=nt_pca0(x,shifts,nkeep,threshold,w)
%[topcs,pwr,y]=nt_pca0(x,shifts,nkeep,threshold,w) - time-shift pca
%
%  topcs: matrix to convert data to PCs
%  pwr: power per PC
%  y: PCs
%
%  x: data matrix
%  shifts: array of shifts to apply
%  nkeep: number of PCs to keep
%  w: weight (see nt_cov)
%  threshold: remove components with normalized eigenvalues smaller than threshold (default: 0)
%
% mean is NOT removed prior to processing
if nargin<1; error('!'); end
if nargin<2||isempty(shifts); shifts=[0]; end
if nargin<3; nkeep=[]; end
if nargin<4||isempty(threshold); threshold=0; end
if nargin<5; w=[]; end
[m,n,o]=size(x);
% remove mean
%x=fold(demean(unfold(x)),size(x,1));
% covariance
if isempty(w);
    c=nt_cov(x,shifts);
else
    c=nt_cov(x,shifts,w);
end
% PCA matrix
if ~isempty(nkeep)
    [topcs,ev]=nt_pcarot(c,nkeep);
else
    [topcs,ev]=nt_pcarot(c);
end
%if ~isempty(nkeep); topcs=topcs(:,1:nkeep); end
% power per PC
pwr=diag(topcs'*c*topcs)/(m*o);
if 0
    idx=find(pwr>=threshold*max(pwr));
    pwr=pwr(idx)';
    topcs=topcs(:,idx);
end
% PCs
if nargout>2
    y=nt_mmat(x,topcs);
end
%% test code
if 0
    x=randn(1000,10);
    [topcs,pwr,y]=nt_pca0(x);
    figure(1); plot(pwr);
    figure(2); subplot 121; plot(y); subplot 122; plot(x*topcs);
end
if 0
    x=zeros(1000,10);
    [topcs,pwr,y]=nt_pca0(x);
    figure(1); plot(pwr);
    figure(2); subplot 121; plot(y); subplot 122; plot(x*topcs);
end
if 0
    x=sin(2*pi*3*(1:1000)'/1000)*randn(1,10);
    x=2*x + randn(size(x));
     [topcs,pwr,y]=nt_pca0(x);
    figure(1); plot(pwr);
    figure(2); subplot 121; plot(x); subplot 122; plot(x*topcs);
end