Description of nt_pca
Home > NoiseTools > nt_pca.m
nt_pca
PURPOSE
[z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
SYNOPSIS
function [z,idx]=nt_pca(x,shifts,nkeep,threshold,w)
DESCRIPTION
[z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
  z: pcs
  idx: x(idx) maps to z
  x: data matrix
  shifts: array of shifts to apply
  keep: number of components shifted regressor PCs to keep (default: all)
  threshold: discard PCs with eigenvalues below this (default: 0)
  w: weights
 Beware: mean is NOT removed prior to processing.
CROSS-REFERENCE INFORMATION
This function calls:
nt_cov [c,tw]=nt_cov(x,shifts,w) - time shift covariance
nt_greetings nt_greetings - display message the first time the toolbox is used
nt_multishift z=nt_multishift(x,shifts,amplitudes) - apply multiple shifts to matrix
nt_pcarot [topcs,eigenvalues]=pcarot(cov,nkeep,threshold,N) - PCA matrix from covariance
This function is called by:
nt_fixsign y=nt_fixsign(x) - flip signs to maximize inter-component correlation
nt_sns1 y=nt_sns1(x,nneigbors,skip,w,threshold) - sensor noise suppression
nt_split_jd [idx,score_vector,todss]=nt_split_dss(x,thresh,depth) - segmentation based on joint diagonalization
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
SOURCE CODE
function [z,idx]=nt_pca(x,shifts,nkeep,threshold,w)
%[z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
%
%  z: pcs
%  idx: x(idx) maps to z
%
%  x: data matrix
%  shifts: array of shifts to apply
%  keep: number of components shifted regressor PCs to keep (default: all)
%  threshold: discard PCs with eigenvalues below this (default: 0)
%  w: weights
%
% Beware: mean is NOT removed prior to processing.
% TODO: reimplement using nt_pca0
nt_greetings;
if nargin<1; error('!'); end
if nargin<2||isempty(shifts); shifts=[0]; end
if nargin<3; nkeep=[]; end
if nargin<4; threshold=[]; end
if nargin<5; w=[]; end
if isnumeric(x)
    [m,n,o]=size(x);
else
    [m,n]=size(x{1});
    o=length(x);
end
% offset of z relative to x
offset=max(0,-min(shifts));
shifts=shifts+offset;           % adjust shifts to make them nonnegative
idx=offset+(1:m-max(shifts));   % x(idx) maps to z
% % remove mean
% x=nt_fold(nt_demean(nt_unfold(x),w),m);
% covariance
c=nt_cov(x,shifts,w);
% PCA matrix
[topcs,evs]=nt_pcarot(c,nkeep,threshold);
%clf; plot(evs); set(gca,'yscale','log'); pause
% apply PCA matrix to time-shifted data
if isnumeric(x)
    z=zeros(numel(idx),size(topcs,2),o);
    for k=1:o
        z(:,:,k)=nt_multishift(x(:,:,k),shifts)*topcs;
    end
else
    z=[];
    for k=1:o
        z{k}(:,:)=nt_multishift(x{k}(:,:),shifts)*topcs;
    end
end