Description of nt_vecmult
Home > NoiseTools > nt_vecmult.m
nt_vecmult
PURPOSE
y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
SYNOPSIS
function x=nt_vecmult(x,v)
DESCRIPTION
y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
 See vecadd, bsxfun
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_fold y=fold(x,epochsize) - fold 2D to 3D
nt_unfold y=nt_fold(x) - unfold 3D to 2D
This function is called by:
nt_bias_fft [c0,c1]=nt_bias_fft(x,freq,nfft) - covariance with and w/o filter bias
nt_cov [c,tw]=nt_cov(x,shifts,w) - time shift covariance
nt_demean [y,mn]=nt_demean(x,w) - remove weighted mean over cols
nt_multishift z=nt_multishift(x,shifts,amplitudes) - apply multiple shifts to matrix
nt_normcol [y,norm]=nt_normcol(x,w) - normalize each column so its weighted msq is 1
nt_regcov r=nt_regcov(cxy,cyy,keep,threshold) - regression matrix from cross covariance
nt_sgram [s,f,t]=nt_sgram(x,window,noverlap,nfft,sr,flags) - spectrogram
nt_sns y=nt_sns(x,nneigbors,skip,w) - sensor noise suppression
nt_sns0 r=nt_sns0(c,nneigbors,skip,wc) - sensor noise suppression
nt_tsxcov [c,tw]=nt_tsxcov(x,y,shifts,w) - cross-covariance of X and time-shifted Y
nt_wpwr [y,tweight]=nt_wpwr(x,w) - weighted power
nt_xcov [c,tw]=nt_xcov(x,y,shifts,w) - cross-covariance of X and time-shifted Y
SOURCE CODE
function x=nt_vecmult(x,v)
%y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
%
% See vecadd, bsxfun
%
% NoiseTools
% check once and for all to save time
persistent bsxfun_exists;
if isempty(bsxfun_exists); bsxfun_exists=(exist('bsxfun')==5); end
[m,n,o]=size(x);
x=nt_unfold(x);
v=nt_unfold(v);
[mm,nn]=size(x);
[mv,nv]=size(v);
if mv==mm
    % same number of rows, v should be column vector (or same size as x)
    if nv==nn
        x=x.*v;
    elseif nv==1
        if bsxfun_exists;
            x=bsxfun(@times,x,v);
            %y=vecop_core(x, v, 1, 2);  % 2 is the opcode of multiplication in vecop_core
        else
            x=x .* repmat(v,1,nn);
        end
    else
        error('V should be row vector');
    end
elseif nv==nn
    % same number of columns, v should be row vector (or same size as x)
    if mv==mm
        x=x.*v;
    elseif mv==1
        if bsxfun_exists;
            x=bsxfun(@times,x,v);
            %y=vecop_core(x, v, 2, 2);  % 2 is the opcode of multiplication in vecop_core
        else
            x=x .* repmat(v,mm,1);
        end
    else
        error('V should be column vector');
    end
else
    error('V and X should have same number of rows or columns');
end
x=nt_fold(x,m);