Description of nt_whoss
Home > NoiseTools > nt_whoss.m
nt_whoss
PURPOSE
size=nt_whoss - total Gbytes used by variables
SYNOPSIS
function varargout=nt_whoss
DESCRIPTION
size=nt_whoss - total Gbytes used by variables
  size: number of Gbytes
 If nargout==0, display Gbytes used
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
nt_cca_crossvalidate [AA,BB,RR,SD]=nt_cca_crossvalidate(xx,yy,shifts,doSurrogate) - CCA with cross-validation
nt_cluster_jd [IDX,todss,SCORE,COVS]=nt_cluster_jd(x,dsr,smooth,flags,init,verbose) - cluster with joint diagonalization
nt_dataview [p,data]=nt_dataview(data,p) - view data sets
nt_index [status,p]=nt_index(name,p,forceUpdate) - index data files & directories
SOURCE CODE
function varargout=nt_whoss
%size=nt_whoss - total Gbytes used by variables
%
%  size: number of Gbytes
%
% If nargout==0, display Gbytes used
s=evalin('caller', 'whos'); % lists variables in caller's workspace
x=cell(1,numel(s));
[x{:}]=deal(s.bytes);       % transfer to cell array
size=sum(cat(1,x{:}));      % transfer to array and sum
size=size/(2^30);           % bytes --> Gbytes
nfiles=numel(fopen('all')); % number of open files
if nargout == 0
    ST=dbstack;
    if numel(ST)>1;
        disp(['Gbytes used: ', num2str(size), ', open files: ', num2str(nfiles), ...
            ', ', ST(2).file,' line ', num2str(ST(2).line)]);
    else
        disp(['Gbytes used: ', num2str(size), ', open files: ', num2str(nfiles)]);
    end
else
    varargout{1}=size;
    varargout{2}=nfiles;
end