Description of test_nt_bias_fft
Home > NoiseTools > test_nt_bias_fft.m
test_nt_bias_fft
PURPOSE
test nt_bias_fft
SYNOPSIS
This is a script file.
DESCRIPTION
 test nt_bias_fft
CROSS-REFERENCE INFORMATION
This function calls:
nt_bias_fft [c0,c1]=nt_bias_fft(x,freq,nfft) - covariance with and w/o filter bias
nt_dss0 [todss,pwr1,pwr2]=nt_dss0(c0,c1,keep1,keep2) - dss from covariance
nt_mmat y=nt_mmat(x,m) - matrix multiplication (with convolution)
nt_spect_plot2 nt_spect_plot2 - plot power spectrum
This function is called by:
SOURCE CODE
% test nt_bias_fft
nsamples=10000;
nchans=10;
SNR=0.0001;
f=20; % Hz
sr=1000;
if 0
x=randn(nsamples,nchans);
x(:,1)=SNR*sin(2*pi*f*(1:nsamples)'/sr);
x=x*randn(nchans);
end
figure(1); clf
nt_spect_plot2(x,512,[],[],sr);
[c0,c1]=nt_bias_fft(x,[20]/sr,2048); [todss,pwr0,pwr1]=nt_dss0(c0,c1);
figure(2); clf;
plot(pwr1./pwr0,'.-')
z=nt_mmat(x,todss);
figure(3); clf
nt_spect_plot2(z,512,[],[],sr);