Description of nt_badChannels
Home > NoiseTools > nt_badChannels.m
nt_badChannels
PURPOSE
iBadChans=nt_badChannels(x,threshRel,threshAbs,prop) - find bad channels using heuristics
SYNOPSIS
function iBadChans=nt_badChannels(x,threshRel,threshAbs,prop)
DESCRIPTION
iBadChans=nt_badChannels(x,threshRel,threshAbs,prop) - find bad channels using heuristics
  iBadChans: bad channel numbers
  x: data
  threshRel: threshold relative to robust std over all channels [default: 3]
  threshAbs: absolute threshold
  prop: proportion beyond which channel is irrecuperable [default 0.7]
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_demean [y,mn]=nt_demean(x,w) - remove weighted mean over cols
nt_greetings nt_greetings - display message the first time the toolbox is used
nt_unfold y=nt_fold(x) - unfold 3D to 2D
nt_wmean y=nt_wmean(x,w,dim) - weighted average
This function is called by:
nt_star2 [y,w,ww]=nt_star2(x,thresh,closest,w) - sensor noise suppression
SOURCE CODE
function iBadChans=nt_badChannels(x,threshRel,threshAbs,prop)
%iBadChans=nt_badChannels(x,threshRel,threshAbs,prop) - find bad channels using heuristics
%
%  iBadChans: bad channel numbers
%
%  x: data
%  threshRel: threshold relative to robust std over all channels [default: 3]
%  threshAbs: absolute threshold
%  prop: proportion beyond which channel is irrecuperable [default 0.7]
%
% NoiseTools
nt_greetings;
if nargin<1; error('!'); end
if nargin<2||isempty(threshRel); threshRel=3; end
if nargin<3; threshAbs=[]; end
if nargin<4; prop=0.7; end
x=nt_unfold(x);
% robust STD
w=ones(size(x));
for iIter=1:4
    xx=nt_demean(x,w);
    STD=sqrt(nt_wmean(xx(:).^2,w(:)));
    w(find(abs(xx)/STD>3))=0;
end
x=nt_demean(x,w);
iBadChans=[];
for iChan=1:size(x,2)
    if numel(find(abs(x(:,iChan))/STD>threshRel)) / size(x,1) > prop
        iBadChans=[iBadChans,iChan];
    end
end
if ~isempty(threshAbs)
    for iChan=1:size(x,2)
        if numel(find(abs(x(:,iChan))>threshAbs)) / size(x,1) > prop
            iBadChans=[iBadChans,iChan];
        end
    end
end