Description of nt_colorlines
Home > NoiseTools > nt_colorlines.m
nt_colorlines
PURPOSE
nt_colorlines(h,permutation) - apply different colors to lines of plot
SYNOPSIS
function nt_colorlines(h,permutation)
DESCRIPTION
nt_colorlines(h,permutation) - apply different colors to lines of plot
  h: handle to plot (default:gca)
  permute: permutation to apply to colors
 Colors are applied to children of h in reverse order (ie in order of plot
 commands).  May produce unexpected results if there are childern other
 than plot lines.\
 NoiseTools
 See nt_stylelines, nt_widthlines.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
nt_bias_cluster [c0,c1,A,todss,pwr0,pwr1]=nt_bias_cluster(x,dsr,flags) - cluster covariance
nt_cov_cluster [c0,c1,A,todss,pwr0,pwr1]=nt_bias_cluster(x,dsr,flags) - cluster covariance
nt_kurtosis [todss,K]=nt_kurtosis(x,nIterations,exponent,w,smooth)- find high-kurtosis components
SOURCE CODE
function nt_colorlines(h,permutation)
%nt_colorlines(h,permutation) - apply different colors to lines of plot
%
%  h: handle to plot (default:gca)
%  permute: permutation to apply to colors
%
% Colors are applied to children of h in reverse order (ie in order of plot
% commands).  May produce unexpected results if there are childern other
% than plot lines.\
%
% NoiseTools
% See nt_stylelines, nt_widthlines.
if nargin<1 || isempty(h); h=gca; end
if nargin<2; permutation=[]; end
colororder=get(h,'colororder');
if ~isempty(permutation);
    colororder=colororder(permutation,:);
end
c=get(h,'children');
for k=1:numel(c);
    set(c(numel(c)-k+1),'color',colororder(1+mod(k-1,size(colororder,1)),:))
end