Description of nt_deglitch
Home > NoiseTools > nt_deglitch.m
nt_deglitch
PURPOSE
[y,B,A]=nt_deglitch(x,glitchList,filt,nfit) - remove temporally localized glitch
SYNOPSIS
function [y,B,A]=nt_deglitch(x,glitchList,nfilt,nfit,advance);
DESCRIPTION
[y,B,A]=nt_deglitch(x,glitchList,filt,nfit) - remove temporally localized glitch
  y: clean data
  B,A: filter coefficients for last estimated event
  x: data to clean (time * channels)
  glitchList: list of glitch positions (cell array if x multichannel)
  nfilt: number of filter coefficients to estimate [default: 10, 10]
  nfit: number of samples over which to fit filter [default: 50]
  advance: number of samples to include before event [default: 3]
 If x is multichannel glitchI should be a cell array.
 See also nt_detrend.
 NoiseTools.
CROSS-REFERENCE INFORMATION
This function calls:
nt_banner h=nt_banner(text,varargin) - annotate with text at head of figure
nt_deglitch [y,B,A]=nt_deglitch(x,glitchList,filt,nfit) - remove temporally localized glitch
nt_destep [y,stepList]=nt_destep(x,thresh,guard,depth,minstep) - remove step glitch from MEG data
nt_greetings nt_greetings - display message the first time the toolbox is used
This function is called by:
nt_deglitch [y,B,A]=nt_deglitch(x,glitchList,filt,nfit) - remove temporally localized glitch
nt_destep [y,stepList]=nt_destep(x,thresh,guard,depth,minstep) - remove step glitch from MEG data
SOURCE CODE
function [y,B,A]=nt_deglitch(x,glitchList,nfilt,nfit,advance);
%[y,B,A]=nt_deglitch(x,glitchList,filt,nfit) - remove temporally localized glitch
%
%  y: clean data
%  B,A: filter coefficients for last estimated event
%
%  x: data to clean (time * channels)
%  glitchList: list of glitch positions (cell array if x multichannel)
%  nfilt: number of filter coefficients to estimate [default: 10, 10]
%  nfit: number of samples over which to fit filter [default: 50]
%  advance: number of samples to include before event [default: 3]
%
% If x is multichannel glitchI should be a cell array.
%
% See also nt_detrend.
%
% NoiseTools.
nt_greetings;
if nargin<2; error('!'); end
if nargin<3; nfilt=[10,10]; end
if nargin<4||isempty(nfit); nfit=50; end
if nargin<5||isempty(advance); advance=3; end
if numel(nfilt)==1; nfilt=[nfilt,nfilt]; end
if ~6==exist('stmcb');
    error('Need function stmcb from signal toolbox');
end
y=x;
if size(x,2)==1 ~iscell(glitchList)
    glitchList={glitchList};
end
for iChan=1:size(x,2)
    events=glitchList{iChan};
    for iEvent=1:numel(events)
        iStart=events(iEvent)-advance;
        glitch=x(iStart+(1:nfit),iChan);
        glitch=glitch-mean(glitch(floor(nfit/2):end));
        %The filter is estimated anew for each event.
        try
            [B,A]=stmcb([glitch;zeros(size(glitch))],nfilt(1),nfilt(2));
            z=filter(B,A,[1;zeros(nfit-1,1)]);
            y(iStart+(1:nfit),iChan)=y(iStart+(1:nfit))-z;
        catch
            warning('stmcb failed (advance too large?)');
        end
    end
end
if ~nargout
    % don't return values, just plot
    %disp(['steps at: ', num2str(stepI(2:end-1))]);
    figure(1); clf; nt_banner('nt_destep');
    xx=[x(:),y(:)];
    lim=[min(xx(:)),max(xx(:))]; lim=[lim(1)-0.1*(lim(2)-lim(1)), lim(2)+0.1*(lim(2)-lim(1))];
    subplot 211; plot([x,y]); xlabel('samples'); ylim(lim); legend('raw','clean'); legend boxoff
    subplot 212;     plot(y,'r'); xlabel('samples'); legend('clean'); legend boxoff
    figure(2); clf
    plot(filter(B,A,[1;zeros(199,1)]),'.-'); xlabel('samples'); title('estimated impulse response of antialiasing filter (last event)');
    clear y B A;
end
% test code
if 0
    N=8;
    Wn=0.25; % CTF corner frequency is 1/4 of sampling rate
    nsamples=100;
    [B,A] = butter(N,Wn);
    y=filter(B,A,ones(nsamples,1));
    BETA0=[1, zeros(1,8), 1, zeros(1,8)];
    fun = @(beta,x)(filter([beta(1),beta(2),beta(3),beta(4),beta(5),beta(6),beta(7),beta(8),beta(9)],...
        [beta(10),beta(11),beta(12),beta(13),beta(14),beta(15),beta(16),beta(17),beta(18)],x));
    x=ones(nsamples,1);
    BETA = nlinfit(x,y,fun,BETA0);
    BETA=BETA/BETA(10);
    BB=BETA(1:9); AA=BETA(10:end);
    figure(1); clf;
    plot([y,filter(BB,AA,ones(size(y)))])
end
if 0
    N=8;
    Wn=0.25; % CTF corner frequency is 1/4 of sampling rate
    [B,A] = butter(N,Wn);
    x=[zeros(1100,1);ones(2000,1)];
    x=filter(B,A,x);
    x=x+0.01*randn(size(x));
    [y,stepList]=nt_destep(x);
    figure(1); clf;
    subplot 211;
    plot([x,y]); legend('raw','step removed')
    subplot 212;
    plot([y,nt_deglitch(y,stepList)]); legend('step removed', 'deglitched');
end
if 0
    N=8;
    Wn=0.25; % CTF corner frequency is 1/4 of sampling rate
    [B,A] = butter(N,Wn);
    x=[zeros(1100,1);ones(1100,1);2*ones(1100,1);3*ones(1100,1);4*ones(1100,1);0*ones(1100,1)];
    %x=filter(B,A,x);
    x=x+0.0*randn(size(x));
    nt_destep(x);
end
if 0
    % this example needs fixing
    x=ft_read_data('/data/meg/litvak/phantom090715_BrainampDBS_20150709_18.ds'); x=permute(x,[2,1,3]); x=x(:,33:306,:);
    x=x(:,100,1);
    [y,stepList]=nt_destep(x,[],[],30);
    figure(1); subplot 211; plot(x);
    subplot 212; plot(nt_deglitch(y,stepList));
end