Description of nt_growmask
Home > NoiseTools > nt_growmask.m
nt_growmask
PURPOSE
ww=nt_growmask(w,margin) - widen mask
SYNOPSIS
function w=nt_growmask(w,margin)
DESCRIPTION
ww=nt_growmask(w,margin) - widen mask
  ww: widened mask (samples * 1 or samples * 1 * trials)
  w: mask
  margin: samples, number of samples by which to widen the mask
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_fold y=fold(x,epochsize) - fold 2D to 3D
nt_unfold y=nt_fold(x) - unfold 3D to 2D
This function is called by:
nt_star2 [y,w,ww]=nt_star2(x,thresh,closest,w) - sensor noise suppression
SOURCE CODE
function w=nt_growmask(w,margin)
%ww=nt_growmask(w,margin) - widen mask
%
%  ww: widened mask (samples * 1 or samples * 1 * trials)
%
%  w: mask
%  margin: samples, number of samples by which to widen the mask
%
% NoiseTools
[m,n,o]=size(w);
w=(w==0);
w=nt_unfold(w);
w=filter(ones(margin+1,1),1,w)>1;
w=flipud(filter(ones(margin+1,1),1,flipud(w))>1);
w=(w==0);
w=nt_fold(w,m);