Description of nt_imagescc
Home > NoiseTools > nt_imagescc.m
nt_imagescc
PURPOSE
nt_imagescc - plot image with symmetric scaling
SYNOPSIS
function nt_imagescc(C)
DESCRIPTION
nt_imagescc - plot image with symmetric scaling
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
nt_cca [A,B,R]=nt_cca(x,y,shifts,C,m,thresh) - canonical correlation
nt_detrend [y,w,r]=nt_detrend(x,order,w,basis,thresh,niter) - robustly remove trend
nt_interpolate_bad_channels y=interpolate_bad_channels(x,iBad,coordinates,n) - interpolate bad channels from good
nt_mcca [A,score,AA]=nt_mcca(C,N) - multiple cca
nt_outliers [w,y]=nt_outliers(x,w,thresh,niter) - detect outliers based on weighted correlation structure
nt_regw [b,z]=nt_regw(y,x,w) - weighted regression
nt_sgram [s,f,t]=nt_sgram(x,window,noverlap,nfft,sr,flags) - spectrogram
nt_spect_plot2 nt_spect_plot2 - plot power spectrum
SOURCE CODE
function nt_imagescc(C)
%nt_imagescc - plot image with symmetric scaling
m=max(abs(C(:)));
imagesc(C,[-m-realmin,m+realmin]);