Description of nt_multishift
Home > NoiseTools > nt_multishift.m
nt_multishift
PURPOSE
z=nt_multishift(x,shifts,amplitudes) - apply multiple shifts to matrix
SYNOPSIS
function z=nt_multishift(x,shifts)
DESCRIPTION
z=nt_multishift(x,shifts,amplitudes) - apply multiple shifts to matrix
   y: result
   x: matrix to shift
   shifts: array of shifts (must be nonnegative)
 X is shifted column by column (all shifts of 1st column, then all
 shifts of second column, etc).
 X may be 1D, 2D or 3D. See also convmtx.
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
nt_multishift z=nt_multishift(x,shifts,amplitudes) - apply multiple shifts to matrix
nt_vecadd y=nt_vecadd(x,v) - add vector to all rows or columns of matrix
nt_vecmult y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
This function is called by:
nt_cov [c,tw]=nt_cov(x,shifts,w) - time shift covariance
nt_multishift z=nt_multishift(x,shifts,amplitudes) - apply multiple shifts to matrix
nt_pca [z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
nt_pca_kmeans [topcs,pwr]=nt_pca_kmeans(x,nkeep) - PCA preceded by kmeans for speed
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsr_nodemean [y,idx,w]=nt_tsr_nodemean(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsxcov [c,tw]=nt_tsxcov(x,y,shifts,w) - cross-covariance of X and time-shifted Y
nt_whiten [A,y]=nt_whiten(x,N) - whiten spectrally using pca
nt_xcov [c,tw]=nt_xcov(x,y,shifts,w) - cross-covariance of X and time-shifted Y
SOURCE CODE
function z=nt_multishift(x,shifts)
%z=nt_multishift(x,shifts,amplitudes) - apply multiple shifts to matrix
%
%   y: result
%
%   x: matrix to shift
%   shifts: array of shifts (must be nonnegative)
%
% X is shifted column by column (all shifts of 1st column, then all
% shifts of second column, etc).
%
% X may be 1D, 2D or 3D. See also convmtx.
%
% NoiseTools
if nargin<2; error('!'); end
if iscell(x)
    for iCell=1:length(x);
        z{iCell}=nt_multishift(x{iCell},shifts);
    end
    return;
end
if size(x,1)<max(shifts); error('shifts should be no larger than nrows'); end
if min(shifts)<0; error('shifts should be nonnegative'); end
shifts=shifts(:)';
nshifts=numel(shifts);
if nshifts==1 && shifts(1)==0;
    z=x;
    return
end
% array of shift indices
N=size(x,1)-max(shifts);
shiftarray=nt_vecadd(nt_vecmult(ones(N,nshifts),shifts),(1:N)');
[m,n,o]=size(x);
z=zeros(N,n*nshifts,o);
for k=1:o
    for j=0:n-1
        y=x(:,j+1,k);
        z(:,j*nshifts+1: j*nshifts+nshifts,k)=y(shiftarray);
    end
end