Description of nt_normrow
Home > NoiseTools > nt_normrow.m
nt_normrow
PURPOSE
y=nt_normcol(x) - normalize each row so its msq is 1
SYNOPSIS
function x=nt_normrow(x)
DESCRIPTION
 y=nt_normcol(x) - normalize each row so its msq is 1
   y: normalized data
   x: data to normalize
CROSS-REFERENCE INFORMATION
This function calls:
nt_normrow y=nt_normcol(x) - normalize each row so its msq is 1
This function is called by:
nt_bias_cluster [c0,c1,A,todss,pwr0,pwr1]=nt_bias_cluster(x,dsr,flags) - cluster covariance
nt_cluster_jd [IDX,todss,SCORE,COVS]=nt_cluster_jd(x,dsr,smooth,flags,init,verbose) - cluster with joint diagonalization
nt_normrow y=nt_normcol(x) - normalize each row so its msq is 1
SOURCE CODE
function x=nt_normrow(x)
% y=nt_normcol(x) - normalize each row so its msq is 1
%
%   y: normalized data
%
%   x: data to normalize
%
if ndims(x)>2
    s=size(x);
    x=nt_normrow(reshape(x,[x,prod(s(2:end))]));
    x=reshape(x,s);
else
    w=1./sqrt(mean(x.^2,2));
    w(find(isnan(w)))=0;
    x=bsxfun(@times,x,w);
end