Description of nt_pcarot
Home > NoiseTools > nt_pcarot.m
nt_pcarot
PURPOSE
[topcs,eigenvalues]=pcarot(cov,nkeep,threshold,N) - PCA matrix from covariance
SYNOPSIS
function [topcs,eigenvalues]=nt_pcarot(cov,nkeep,threshold,N)
DESCRIPTION
 [topcs,eigenvalues]=pcarot(cov,nkeep,threshold,N) - PCA matrix from covariance
  topcs: PCA rotation matrix
  eigenvalues: PCA eigenvalues
  cov: covariance matrix
  nkeep: number of component to keep
  thresholds: discard components below this threshold
  N: eigs' K parameter (if absent: use eig)
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
nt_dss0 [todss,pwr1,pwr2]=nt_dss0(c0,c1,keep1,keep2) - dss from covariance
nt_inpaint function y=nt_inpaint(x,w) - weighted interpolation based on correlation structure
nt_outliers [w,y]=nt_outliers(x,w,thresh,niter) - detect outliers based on weighted correlation structure
nt_pca [z,idx]=nt_pca(x,shifts,nkeep,threshold,w) - time-shift pca
nt_pca0 [topcs,pwr,y]=nt_pca0(x,shifts,nkeep,threshold,w) - time-shift pca
nt_qpca0 [tosquares,quads,D]=nt_qpca0(x,npcs,nsmooth,nquads) - quadratic PCA
nt_regcov r=nt_regcov(cxy,cyy,keep,threshold) - regression matrix from cross covariance
nt_sns0 r=nt_sns0(c,nneigbors,skip,wc) - sensor noise suppression
nt_star [y,w,ww]=nt_star(x,thresh,closest,depth) - sensor noise suppression
nt_star2 [y,w,ww]=nt_star2(x,thresh,closest,w) - sensor noise suppression
nt_whiten [A,y]=nt_whiten(x,N) - whiten spectrally using pca
SOURCE CODE
function [topcs,eigenvalues]=nt_pcarot(cov,nkeep,threshold,N)
% [topcs,eigenvalues]=pcarot(cov,nkeep,threshold,N) - PCA matrix from covariance
%
%  topcs: PCA rotation matrix
%  eigenvalues: PCA eigenvalues
%
%  cov: covariance matrix
%  nkeep: number of component to keep
%  thresholds: discard components below this threshold
%  N: eigs' K parameter (if absent: use eig)
%
% NoiseTools
if nargin<4; N=[]; end
if nargin<3; threshold=[]; end
if nargin<2; nkeep=[]; end
if ~isempty(N);
    [V, S] = eigs(cov,N) ;
else
    [V, S] = eig(cov) ;
end
V=real(V);
S=real(S);
[eigenvalues, idx] = sort(diag(S)', 'descend') ;
topcs = V(:,idx);
% truncate
if ~isempty (threshold)
    ii=find(eigenvalues/eigenvalues(1)>threshold);
    topcs=topcs(:,ii);
    eigenvalues=eigenvalues(ii);
end
if ~isempty(nkeep)
    nkeep=min(nkeep,size(topcs,2));
    topcs=topcs(:,1:nkeep);
    eigenvalues=eigenvalues(1:nkeep);
end