Description of nt_regcov
Home > NoiseTools > nt_regcov.m
nt_regcov
PURPOSE
r=nt_regcov(cxy,cyy,keep,threshold) - regression matrix from cross covariance
SYNOPSIS
function r=nt_regcov(cxy,cyy,keep,threshold)
DESCRIPTION
r=nt_regcov(cxy,cyy,keep,threshold) - regression matrix from cross covariance
  r: matrix to apply to regressor to best model data
  cxy: cross-covariance matrix between data and regressor
  cyy: covariance matrix of regressor
  keep: number of regressor PCs to keep (default: all)
  threshold: eigenvalue threshold for discarding regressor PCs (default: 0)
CROSS-REFERENCE INFORMATION
This function calls:
nt_pcarot [topcs,eigenvalues]=pcarot(cov,nkeep,threshold,N) - PCA matrix from covariance
nt_vecmult y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
This function is called by:
nt_tsr [y,idx,w]=nt_tsr(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsr_nodemean [y,idx,w]=nt_tsr_nodemean(x,ref,shifts,wx,wref,keep,thresh) - time-shift regression (TSPCA)
nt_tsregress [z,idx]=nt_tsregress(x,y,shifts,xw,yw,keep,threshold) - time-shift regression
SOURCE CODE
function r=nt_regcov(cxy,cyy,keep,threshold)
%r=nt_regcov(cxy,cyy,keep,threshold) - regression matrix from cross covariance
%
%  r: matrix to apply to regressor to best model data
%
%  cxy: cross-covariance matrix between data and regressor
%  cyy: covariance matrix of regressor
%  keep: number of regressor PCs to keep (default: all)
%  threshold: eigenvalue threshold for discarding regressor PCs (default: 0)
if nargin<4; threshold=[]; end
if nargin<3; keep=[]; end
if nargin<2; error('!'); end
% PCA of regressor
[topcs,eigenvalues]=nt_pcarot(cyy);
% discard negligible regressor PCs
if ~isempty(keep)
    keep=max(keep,size(topcs,2));
    topcs=topcs(:,1:keep);
    eigenvalues=eigenvalues(1:keep);
end
if ~isempty(threshold)
    idx=find(eigenvalues/max(eigenvalues)>threshold);
    topcs=topcs(:,idx);
    eigenvalues=eigenvalues(idx);
end
% cross-covariance between data and regressor PCs
cxy=cxy';
r=topcs'*cxy;
% projection matrix from regressor PCs
r=nt_vecmult(r,1./eigenvalues');
% projection matrix from regressors
r=topcs*r;
return