Description of nt_unique
Home > NoiseTools > nt_unique.m
nt_unique
PURPOSE
[C,IA,IC,N] = nt_unique(A, varargin) - unique with counts
SYNOPSIS
function [C,IA,IC,N] = nt_unique(A, varargin)
DESCRIPTION
[C,IA,IC,N] = nt_unique(A, varargin) - unique with counts
  N: number of occurrences
 See unique for definition of other variables.
 NoiseTools
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
nt_inpaint function y=nt_inpaint(x,w) - weighted interpolation based on correlation structure
nt_outliers [w,y]=nt_outliers(x,w,thresh,niter) - detect outliers based on weighted correlation structure
nt_star2 [y,w,ww]=nt_star2(x,thresh,closest,w) - sensor noise suppression
SOURCE CODE
function [C,IA,IC,N] = nt_unique(A, varargin)
%[C,IA,IC,N] = nt_unique(A, varargin) - unique with counts
%
%  N: number of occurrences
%
% See unique for definition of other variables.
%
% NoiseTools
[Asorted,iSort]=sortrows(A);
[~,iReverse]=sort(iSort);
[C,IA,IC]=unique(Asorted,varargin{:});
p=find([1;diff(IC);1]);
N=diff(p);
IA=iSort(IA);
IC=IC(iReverse);