Description of nt_wpwr
Home > NoiseTools > nt_wpwr.m
nt_wpwr
PURPOSE
[y,tweight]=nt_wpwr(x,w) - weighted power
SYNOPSIS
function [y,tweight]=nt_wpwr(x,w)
DESCRIPTION
[y,tweight]=nt_wpwr(x,w) - weighted power
  y: weighted ssq of x
  tweight: total weight
  x: data
  w: weight
CROSS-REFERENCE INFORMATION
This function calls:
nt_unfold y=nt_fold(x) - unfold 3D to 2D
nt_vecmult y=nt_vecmult(x,v) - multiply all rows or columns of matrix by vector
This function is called by:
nt_dss_repeat_cluster y=nt_dss_repeat_cluster(x,nkeep,cluster_size) - dss within clusters
nt_inpaint function y=nt_inpaint(x,w) - weighted interpolation based on correlation structure
nt_outliers [w,y]=nt_outliers(x,w,thresh,niter) - detect outliers based on weighted correlation structure
nt_sns_cluster y=nt_sns_cluster(x,nneigbors,cluster_size) - sensor noise suppression within clusters
nt_star [y,w,ww]=nt_star(x,thresh,closest,depth) - sensor noise suppression
nt_star2 [y,w,ww]=nt_star2(x,thresh,closest,w) - sensor noise suppression
SOURCE CODE
function [y,tweight]=nt_wpwr(x,w)
%[y,tweight]=nt_wpwr(x,w) - weighted power
%
%  y: weighted ssq of x
%  tweight: total weight
%
%  x: data
%  w: weight
%
if nargin<2; w=[]; end
x=nt_unfold(x);
w=nt_unfold(w);
if isempty(w)
    y=sum(x(:).^2);
    tweight=numel(x);
else
    x=nt_vecmult(x,w);
    y=sum(x(:).^2);
    tweight=sum(w(:));
end
if nargout==0;
    disp(num2str(y));
    clear y tweight
end